title: Shanshan Chen 
markdown: kramdown
url: "https://ShanshanChen-Biostat.github.io"
description: Statistical signal processing, Bayesian time-series, and AI for wearable and digital health sensing data
theme: jekyll-theme-primer


github:
  is_project_page: FALSE
  license: ""
  repository_url: "https://shanshanchen-biostat.github.io"
  repository: "ShanshanChen-Biostat/shanshanchen-biostat.github.io"


 
google_analytics: UA-37790622-1
google-site-verification: gWoCO0HYyb7EMMOA38puaAJT2u5K0mLfeZkkKUa9VFE
show_downloads: FALSE
nav:
  - title: "Research"
    url: /Research.html
  - title: "Teaching"
    url: /Teaching.html
  - title: "Software"
    url: /Tools.html

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
include:
  - Actigraphy.md
  - EnergyMet.md
  - WearableEvaluation.md
  - Collaborative.md
  - Tools.md
  - WearableGait.md
  - Rprogramming.md
  - SleepArchitecture.md

  
  
