title: Shanshan Chen 
markdown: kramdown
url: "https://ShanshanChen-Biostat.github.io"
description: GitHub Homepage
theme: jekyll-theme-primer
github:
  repository_url: https://shanshanchen-biostat.github.io
github:
  is_project_page: FALSE
google_analytics: UA-37790622-1
sidebar:
    - name: "About"
      url: "/index.html/"
      weight: 1
    - name: "Research"
      url: "/EnergyMet.html/"
      weight: 2
 
include:
  - Actigraphy.md
  - EnergyMet.md
  - WearableEvaluation.md
  - Collaborative Research
  - Tools for Researchers
  
  
