title: Shanshan Chen
url: "https://ShanshanChen-Biostat.github.io"
description: GitHub Homepage
theme: jekyll-theme-leap-day
include:
  - Actigraphy.md
  - EnergyMet.md
  - Collaborative Research
  - Tools for Researchers
  
  
